dapp/urls.py
from django.urls import path,include
from dapp import views
app_name='dapp'

urlpatterns = [
    path('',views.doc,name='doc'),
    path('doclist', views.doclist, name='doclist'),
    path('<str:c_slug>/',views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProCatDetail, name='ProCatDetail'),
    path('appoinment',views.demo, name='appoinment')
]

doc/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dapp/models.py
from django.db import models
from django.urls import reverse
import datetime

# Create your models here.
class department(models.Model):
    dep_name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    # image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('dep_name',)
        verbose_name='department'
        verbose_name_plural='department'
    def get_url(self):
        return reverse("dapp:products_by_category",args=[self.slug])
    def __str__(self):
        return '{}'.format(self.dep_name)


class docters(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)
    category=models.ForeignKey(department,on_delete=models.CASCADE)



    def get_url(self):
         return reverse("dapp:ProCatDetail",args=[self.category.slug,self.slug])

    def __str__(self):
         return '{}'.format(self.name)

class appoinment(models.Model):
    name = models.CharField(max_length=250,blank=True)
    email = models.EmailField(max_length=70,blank=True)
    phone = models.IntegerField(max_length=10)
    date = models.DateField(auto_now_add=True)
    departments = models.CharField(max_length=25,blank=True)
    doctor = models.CharField(max_length=25,blank=True)
class Task(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=100)
    priority = models.IntegerField()
    date = models.DateField(default=datetime.date.today)

dapp/views.py
from django.shortcuts import render,get_object_or_404
from.models import department,docters,appoinment,Task
from django.views.generic import ListView
from django.views.generic.detail import DetailView

# Create your views here.
def doc(request):
    obj=department.objects.all()
    return render(request,'index.html',{'dep':obj})

def doclist(request):
    obj=docters.objects.all()
    return render(request,'docters.html',{'doc':obj})
def CategoryView(request, cats=None):
    category_post = docters.objects.filter(category=cats)
    return(request,'categories.hml',{'cats':cats,'category_post':category_post})
def allProdCat(request,c_slug=None):
    c_page=get_object_or_404(department,slug=c_slug)
    products_list=docters.objects.filter(category=c_page)

    return render(request,'categories.html',{'category':c_page,'product':products_list})
def ProCatDetail(request,c_slug,product_slug):
    try:
        product = docters.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
            raise e
    return render(request,'product.html',{'product':product})


# def demo(request):
#     product1 = appoinment.objects.all()
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         department = request.POST.get('department')
#         date= request.POST.get('date')
#         email= request.Post.get('email')
#         phone = request.Post.get('phone')
#         obj = appoinment(name=name,department=department,phone=phone,date=date,email =email)
#         obj.save()
#         return render(request, "appoinment.html", {'product': product1})
#     return render(request, "appoinment.html")
def demo(request):
    product1 = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('name')
        priority = request.POST.get('priority')
        date= request.POST.get('date')
        obj = Task(name=name, priority=priority,date=date)
        obj.save()
        return render(request, "home.html", {'product': product1})
    return render(request, 'home.html')

templates/appoinment.html
<section id="appointment" class="appointment section-bg">
      <div class="container">

        <div class="section-title">
          <h2>Make an Appointment</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <form action="forms/appointment.php" method="post" role="form" class="php-email-form">
          <div class="form-row">
            <div class="col-md-4 form-group">
              <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars">
              <div class="validate"></div>
            </div>
            <div class="col-md-4 form-group">
              <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email">
              <div class="validate"></div>
            </div>
            <div class="col-md-4 form-group">
              <input type="tel" class="form-control" name="phone" id="phone" placeholder="Your Phone" data-rule="minlen:4" data-msg="Please enter at least 4 chars">
              <div class="validate"></div>
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-4 form-group">
              <input type="datetime" name="date" class="form-control datepicker" id="date" placeholder="Appointment Date" data-rule="minlen:4" data-msg="Please enter at least 4 chars">
              <div class="validate"></div>
            </div>
            <div class="col-md-4 form-group">
              <select name="department" id="department" class="form-control">
                <option value="">Select Department</option>
                <option value="Department 1">Department 1</option>
                <option value="Department 2">Department 2</option>
                <option value="Department 3">Department 3</option>
              </select>
              <div class="validate"></div>
            </div>
            <div class="col-md-4 form-group">
              <select name="doctor" id="doctor" class="form-control">
                <option value="">Select Doctor</option>
                <option value="Doctor 1">Doctor 1</option>
                <option value="Doctor 2">Doctor 2</option>
                <option value="Doctor 3">Doctor 3</option>
              </select>
              <div class="validate"></div>
            </div>
          </div>

          <div class="form-group">
            <textarea class="form-control" name="message" rows="5" placeholder="Message (Optional)"></textarea>
            <div class="validate"></div>
          </div>
          <div class="mb-3">
            <div class="loading">Loading</div>
            <div class="error-message"></div>
            <div class="sent-message">Your appointment request has been sent successfully. Thank you!</div>
          </div>
          <div class="text-center"><button type="submit">Make an Appointment</button></div>
        </form>

      </div>
    </section><!-- End Appointment Section -->

templates/categories.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Medilab Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Medilab - v2.1.1
  * Template URL: https://bootstrapmade.com/medilab-free-medical-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-none d-lg-flex align-items-center fixed-top">
    <div class="container d-flex">
      <div class="contact-info mr-auto">
        <i class="icofont-envelope"></i> <a href="mailto:contact@example.com">contact@example.com</a>
        <i class="icofont-phone"></i> +1 5589 55488 55
        <i class="icofont-google-map"></i> A108 Adam Street, NY
      </div>
      <div class="social-links">
        <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
        <a href="#" class="facebook"><i class="icofont-facebook"></i></a>
        <a href="#" class="instagram"><i class="icofont-instagram"></i></a>
        <a href="#" class="skype"><i class="icofont-skype"></i></a>
        <a href="#" class="linkedin"><i class="icofont-linkedin"></i></i></a>
      </div>
    </div>
  </div>

 <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo mr-auto"><a href="{% url 'dapp:doc' %}">Medilab</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="{% url 'dapp:doc' %}">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="{% url 'dapp:doclist' %}">Doctors</a></li>
          <li class="drop-down"><a href="">Department</a>
            <ul>
              {% for dep in dep %}
              <li><a href="{% url 'dapp:products_by_category' dep.dep_name %}">{{dep.dep_name}}</a></li>
              {% endfor %}

            </ul>
          </li>
          <li><a href="#contact">Contact</a></li>

        </ul>
      </nav><!-- .nav-menu -->

      <a href="{% url 'dapp:appoinment' %}" class="appointment-btn scrollto">Make an Appointment</a>

    </div>
  </header><!-- End Header -->
  <!-- ======= Hero Section ======= -->
<section id="doctors" class="doctors">
      <div class="container">
<div class="section-title">
          <h2>Doctors</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>


{% for doc in product%}
<div class="row">

          <div class="col-lg-6">
            <div class="member d-flex align-items-start">
              <div class="pic"><img src="{{doc.image.url}}" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>{{doc.name}}</h4>
                <span>{{doc.category}}</span>
                <p>{{doc.desc}}</p>
                <div class="social">
                  <a href=""><i class="ri-twitter-fill"></i></a>
                  <a href=""><i class="ri-facebook-fill"></i></a>
                  <a href=""><i class="ri-instagram-fill"></i></a>
                  <a href=""> <i class="ri-linkedin-box-fill"></i> </a>
                </div>
              </div>
            </div>
          </div></div>
    {% endfor %}

        </div>

      </div>
    </section><!-- End Doctors Section -->

templates/docters.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Medilab Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Medilab - v2.1.1
  * Template URL: https://bootstrapmade.com/medilab-free-medical-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-none d-lg-flex align-items-center fixed-top">
    <div class="container d-flex">
      <div class="contact-info mr-auto">
        <i class="icofont-envelope"></i> <a href="mailto:contact@example.com">contact@example.com</a>
        <i class="icofont-phone"></i> +1 5589 55488 55
        <i class="icofont-google-map"></i> A108 Adam Street, NY
      </div>
      <div class="social-links">
        <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
        <a href="#" class="facebook"><i class="icofont-facebook"></i></a>
        <a href="#" class="instagram"><i class="icofont-instagram"></i></a>
        <a href="#" class="skype"><i class="icofont-skype"></i></a>
        <a href="#" class="linkedin"><i class="icofont-linkedin"></i></i></a>
      </div>
    </div>
  </div>

  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo mr-auto"><a href="{% url 'dapp:doc' %}">Medilab</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="{% url 'dapp:doc' %}">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="{% url 'dapp:doclist' %}">Doctors</a></li>
          <li class="drop-down"><a href="">Department</a>
            <ul>
              {% for dep in dep %}
              <li><a href="{% url 'dapp:products_by_category' dep.dep_name %}">{{dep.dep_name}}</a></li>
              {% endfor %}

            </ul>
          </li>
          <li><a href="#contact">Contact</a></li>

        </ul>
      </nav><!-- .nav-menu -->

      <a href="{% url 'dapp:appoinment' %}" class="appointment-btn scrollto">Make an Appointment</a>

    </div>
  </header><!-- End Header -->
  <!-- ======= Hero Section ======= -->
<section id="doctors" class="doctors">
      <div class="container">

        <div class="section-title">
          <h2>Doctors</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>
{% for doc in doc %}
        <div class="row">

          <div class="col-lg-6">
            <div class="member d-flex align-items-start">
              <div class="pic"><a href="{{doc.get_url}}"><img src="{{doc.image.url}}" class="img-fluid" alt=""></a> </div>
              <div class="member-info">
                <h4>{{doc.name}}</h4>
                <span>{{doc.category}}</span>
                <p>{{doc.desc}}</p>
                <div class="social">
                  <a href=""><i class="ri-twitter-fill"></i></a>
                  <a href=""><i class="ri-facebook-fill"></i></a>
                  <a href=""><i class="ri-instagram-fill"></i></a>
                  <a href=""> <i class="ri-linkedin-box-fill"></i> </a>
                </div>
              </div>
            </div>
          </div>
            {% endfor %}

          <!--<div class="col-lg-6 mt-4 mt-lg-0">-->
            <!--<div class="member d-flex align-items-start">-->
              <!--<div class="pic"><img src="assets/img/doctors/doctors-2.jpg" class="img-fluid" alt=""></div>-->
              <!--<div class="member-info">-->
                <!--<h4>Sarah Jhonson</h4>-->
                <!--<span>Anesthesiologist</span>-->
                <!--<p>Aut maiores voluptates amet et quis praesentium qui senda para</p>-->
                <!--<div class="social">-->
                  <!--<a href=""><i class="ri-twitter-fill"></i></a>-->
                  <!--<a href=""><i class="ri-facebook-fill"></i></a>-->
                  <!--<a href=""><i class="ri-instagram-fill"></i></a>-->
                  <!--<a href=""> <i class="ri-linkedin-box-fill"></i> </a>-->
                <!--</div>-->
              <!--</div>-->
            <!--</div>-->
          <!--</div>-->

          <!--<div class="col-lg-6 mt-4">-->
            <!--<div class="member d-flex align-items-start">-->
              <!--<div class="pic"><img src="assets/img/doctors/doctors-3.jpg" class="img-fluid" alt=""></div>-->
              <!--<div class="member-info">-->
                <!--<h4>William Anderson</h4>-->
                <!--<span>Cardiology</span>-->
                <!--<p>Quisquam facilis cum velit laborum corrupti fuga rerum quia</p>-->
                <!--<div class="social">-->
                  <!--<a href=""><i class="ri-twitter-fill"></i></a>-->
                  <!--<a href=""><i class="ri-facebook-fill"></i></a>-->
                  <!--<a href=""><i class="ri-instagram-fill"></i></a>-->
                  <!--<a href=""> <i class="ri-linkedin-box-fill"></i> </a>-->
                <!--</div>-->
              <!--</div>-->
            <!--</div>-->
          <!--</div>-->

          <!--<div class="col-lg-6 mt-4">-->
            <!--<div class="member d-flex align-items-start">-->
              <!--<div class="pic"><img src="assets/img/doctors/doctors-4.jpg" class="img-fluid" alt=""></div>-->
              <!--<div class="member-info">-->
                <!--<h4>Amanda Jepson</h4>-->
                <!--<span>Neurosurgeon</span>-->
                <!--<p>Dolorum tempora officiis odit laborum officiis et et accusamus</p>-->
                <!--<div class="social">-->
                  <!--<a href=""><i class="ri-twitter-fill"></i></a>-->
                  <!--<a href=""><i class="ri-facebook-fill"></i></a>-->
                  <!--<a href=""><i class="ri-instagram-fill"></i></a>-->
                  <!--<a href=""> <i class="ri-linkedin-box-fill"></i> </a>-->
                <!--</div>-->
              <!--</div>-->
            <!--</div>-->
          <!--</div>-->

        </div>

      </div>
    </section><!-- End Doctors Section -->

templates/home.html
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner" style="width:'col-md-12px';height:100px">
                <div class="banner-title">Todo</div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
<form method="post">
    {% csrf_token %}
    <div class="form-group">
    <input type="text" name="name" class="form-control" placeholder="name">
    </div>
    <div class="form-group">
        <input type="number" name="priority"  class="form-control" placeholder="docter name">
    </div>
    <div class="form-group">
        <input type="date" name="date"  class="form-control" placeholder="date">
    </div>
    <input type="submit" value="submit" class="btn btn-success">

</form>

             </div>
        <div class="col-md-6">
            <h2> appoinment</h2>
            {% for i in product %}
            <div class="shadow card">
            <div class="card-body">
                <div class="card title">{{ i.name}}</div>
                    <p><b>{{i.priority}}<br>{{i.date}}</b></p>


            </div>
        </div>
             {% endfor %}
            </div>

    </div>

    </div>


{% endblock %}